# Generated by Django 2.0.6 on 2018-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_datasets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcitation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
