# Generated by Django 2.0.6 on 2018-08-02 16:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('context_datasets', '0002_datasetcitation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcitation',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
