# Generated by Django 2.1.5 on 2019-02-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context_datasets', '0012_auto_20190202_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetmention',
            old_name='publication',
            new_name='article',
        ),
        migrations.AddField(
            model_name='workdatasetmention',
            name='data_set_citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context_datasets.DataSetCitation'),
        ),
        migrations.AddField(
            model_name='workdatasetmention',
            name='data_set_citation_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context_datasets.DataSetCitationData'),
        ),
        migrations.AddField(
            model_name='workdatasetmention',
            name='mention_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis')], default='mention', max_length=255),
        ),
    ]
