# Generated by Django 2.1.5 on 2019-02-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_datasets', '0013_auto_20190203_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcitation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetmention',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdatasetcitation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdatasetmention',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workresearchfield',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workresearchmethod',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
