# Generated by Django 2.1.5 on 2019-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_datasets', '0014_auto_20190203_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmention',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workdatasetcitation',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workdatasetmention',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workresearchfield',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workresearchmethod',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
