# Generated by Django 2.1.7 on 2019-03-27 18:19

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet', '0022_article_data_work_log'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context', '0004_auto_20190305_1858'),
        ('sourcenet_datasets', '0017_auto_20190327_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('value_in_context', models.TextField(blank=True, null=True)),
                ('value_index', models.IntegerField(blank=True, default=0, null=True)),
                ('value_length', models.IntegerField(blank=True, default=0, null=True)),
                ('canonical_index', models.IntegerField(blank=True, default=0, null=True)),
                ('value_word_number_start', models.IntegerField(blank=True, default=0, null=True)),
                ('value_word_number_end', models.IntegerField(blank=True, default=0, null=True)),
                ('paragraph_number', models.IntegerField(blank=True, default=0, null=True)),
                ('context_before', models.TextField(blank=True, null=True)),
                ('context_after', models.TextField(blank=True, null=True)),
                ('capture_method', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.TextField(blank=True, null=True)),
                ('uuid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mention_type', models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis')], default='mention', max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('start_index', models.IntegerField(blank=True, null=True)),
                ('occurrence_number', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcenet.Article')),
                ('article_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcenet.Article_Data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datareference',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datareference',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project')], default='mention', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project')], default='mention', max_length=255),
        ),
        migrations.AlterField(
            model_name='workdatasetcitation',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project')], default='mention', max_length=255),
        ),
        migrations.AddField(
            model_name='datacontext',
            name='data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcenet_datasets.DataReference'),
        ),
        migrations.AddField(
            model_name='datacontext',
            name='data_set_citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcenet_datasets.DataSetCitation'),
        ),
        migrations.AddField(
            model_name='datacontext',
            name='data_set_citation_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcenet_datasets.DataSetCitationData'),
        ),
        migrations.AddField(
            model_name='datacontext',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='datacontext',
            name='work_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Work_Log'),
        ),
    ]
