# Generated by Django 2.1.7 on 2019-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sourcenet', '0022_article_data_work_log'),
        ('context', '0004_auto_20190305_1858'),
        ('context_data', '0018_auto_20190327_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataContext',
            new_name='DataReferenceContext',
        ),
        migrations.RenameModel(
            old_name='DataMention',
            new_name='DataReferenceMention',
        ),
        migrations.AddField(
            model_name='datareference',
            name='related_data_sets',
            field=models.ManyToManyField(related_name='related_data_set_set', to='context_data.DataSet'),
        ),
        migrations.AlterField(
            model_name='datareference',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project'), ('statistic', 'statistic')], default='mention', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project'), ('statistic', 'statistic')], default='mention', max_length=255),
        ),
        migrations.AlterField(
            model_name='workdatasetcitation',
            name='citation_type',
            field=models.CharField(choices=[('mention', 'mention'), ('analysis', 'analysis'), ('project', 'project'), ('statistic', 'statistic')], default='mention', max_length=255),
        ),
    ]
