# Generated by Django 2.2.1 on 2019-05-08 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context_data', '0020_auto_20190502_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('canonical', 'Canonical'), ('text', 'Text'), ('html', 'HTML'), ('json', 'JSON'), ('xml', 'XML'), ('other', 'Other'), ('none', 'None')], default='none', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_identifier', models.TextField(blank=True, null=True)),
                ('note_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_data.DataSet')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['data_set', 'last_modified', 'create_date'],
                'abstract': False,
            },
        ),
    ]
