# Generated by Django 2.2.1 on 2019-05-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context_data', '0021_datasetnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSetNotes',
            new_name='DataSetNote',
        ),
    ]
