# Generated by Django 3.1.2 on 2020-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_data', '0022_auto_20190508_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetnote',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
