UPDATE django_content_type SET app_label='context_datasets' WHERE app_label='sourcenet_datasets';
UPDATE django_migrations SET app='context_datasets' WHERE app='sourcenet_datasets';

/*
-- Get the index names of all the indexes for tables in this application.
--     (and get each twice for ease of making ALTER INDEX statements)
SELECT index_name, index_name
FROM pg_indexes
WHERE tablename LIKE 'sourcenet_datasets_%';
*/

ALTER INDEX sourcenet_datasets_dataset_pkey RENAME TO context_datasets_dataset_pkey;
ALTER INDEX sourcenet_datasets_datasetcitation_pkey RENAME TO context_datasets_datasetcitation_pkey;
ALTER INDEX sourcenet_datasets_datasetidentifier_pkey RENAME TO context_datasets_datasetidentifier_pkey;
ALTER INDEX sourcenet_datasets_datasetmention_pkey RENAME TO context_datasets_datasetmention_pkey;
ALTER INDEX sourcenet_datasets_datasetcitation_article_id_14c1317d RENAME TO context_datasets_datasetcitation_article_id_14c1317d;
ALTER INDEX sourcenet_datasets_datasetcitation_article_data_id_a48fb867 RENAME TO context_datasets_datasetcitation_article_data_id_a48fb867;
ALTER INDEX sourcenet_datasets_datasetcitation_data_set_id_c9cb9456 RENAME TO context_datasets_datasetcitation_data_set_id_c9cb9456;
ALTER INDEX sourcenet_datasets_datasetidentifier_dataset_id_efeacba2 RENAME TO context_datasets_datasetidentifier_dataset_id_efeacba2;
ALTER INDEX sourcenet_datasets_datasetmention_article_data_id_7e3fc13d RENAME TO context_datasets_datasetmention_article_data_id_7e3fc13d;
ALTER INDEX sourcenet_datasets_datasetmention_data_set_citation_id_bbd36ee5 RENAME TO context_datasets_datasetmention_data_set_citation_id_bbd36ee5;
ALTER INDEX sourcenet_datasets_datasetcitationdata_pkey RENAME TO context_datasets_datasetcitationdata_pkey;
ALTER INDEX sourcenet_datasets_datasetcitationdata_article_data_id_f539ed21 RENAME TO context_datasets_datasetcitationdata_article_data_id_f539ed21;
ALTER INDEX sourcenet_datasets_dataset_data_set_citation_id_2c04e263 RENAME TO context_datasets_dataset_data_set_citation_id_2c04e263;
ALTER INDEX sourcenet_datasets_dataset_data_set_citation_data_id_3ddd93be RENAME TO context_datasets_dataset_data_set_citation_data_id_3ddd93be;
ALTER INDEX sourcenet_datasets_dataset_parent_data_set_id_97e817a9 RENAME TO context_datasets_dataset_parent_data_set_id_97e817a9;
ALTER INDEX sourcenet_datasets_datasetcitationdata_work_log_id_4955c894 RENAME TO context_datasets_datasetcitationdata_work_log_id_4955c894;
ALTER INDEX sourcenet_datasets_workdatasetcitation_pkey RENAME TO context_datasets_workdatasetcitation_pkey;
ALTER INDEX sourcenet_datasets_workdatasetmention_pkey RENAME TO context_datasets_workdatasetmention_pkey;
ALTER INDEX sourcenet_datasets_workresearchfield_pkey RENAME TO context_datasets_workresearchfield_pkey;
ALTER INDEX sourcenet_datasets_workresearchmethod_pkey RENAME TO context_datasets_workresearchmethod_pkey;
ALTER INDEX sourcenet_datasets_workdatasetcitation_article_id_c6e3d9c5 RENAME TO context_datasets_workdatasetcitation_article_id_c6e3d9c5;
ALTER INDEX sourcenet_datasets_workdatasetcitation_article_data_id_30d2c970 RENAME TO context_datasets_workdatasetcitation_article_data_id_30d2c970;
ALTER INDEX sourcenet_datasets_workdatasetcitation_data_set_id_f4598e93 RENAME TO context_datasets_workdatasetcitation_data_set_id_f4598e93;
ALTER INDEX sourcenet_datasets_workdatasetcitation_work_log_id_073c3bc2 RENAME TO context_datasets_workdatasetcitation_work_log_id_073c3bc2;
ALTER INDEX sourcenet_datasets_workdatasetmention_article_id_cdaaeb8a RENAME TO context_datasets_workdatasetmention_article_id_cdaaeb8a;
ALTER INDEX sourcenet_datasets_workdatasetmention_article_data_id_624b0f94 RENAME TO context_datasets_workdatasetmention_article_data_id_624b0f94;
ALTER INDEX sourcenet_datasets_workdatasetmention_work_log_id_6b397f64 RENAME TO context_datasets_workdatasetmention_work_log_id_6b397f64;
ALTER INDEX sourcenet_datasets_workresearchfield_article_id_b4656ea0 RENAME TO context_datasets_workresearchfield_article_id_b4656ea0;
ALTER INDEX sourcenet_datasets_workresearchfield_article_data_id_bcd106b6 RENAME TO context_datasets_workresearchfield_article_data_id_bcd106b6;
ALTER INDEX sourcenet_datasets_workresearchfield_work_log_id_2cf656b5 RENAME TO context_datasets_workresearchfield_work_log_id_2cf656b5;
ALTER INDEX sourcenet_datasets_workresearchmethod_article_id_17ceaecf RENAME TO context_datasets_workresearchmethod_article_id_17ceaecf;
ALTER INDEX sourcenet_datasets_workresearchmethod_article_data_id_55d92355 RENAME TO context_datasets_workresearchmethod_article_data_id_55d92355;
ALTER INDEX sourcenet_datasets_workresearchmethod_work_log_id_f5d7f1e0 RENAME TO context_datasets_workresearchmethod_work_log_id_f5d7f1e0;
ALTER INDEX sourcenet_datasets_datasetcitation_work_log_id_512cc22a RENAME TO context_datasets_datasetcitation_work_log_id_512cc22a;
ALTER INDEX sourcenet_datasets_datasetmention_publication_id_1dd0cdd5 RENAME TO context_datasets_datasetmention_publication_id_1dd0cdd5;
ALTER INDEX sourcenet_datasets_datasetmention_work_log_id_3bdccee3 RENAME TO context_datasets_datasetmention_work_log_id_3bdccee3;
ALTER INDEX sourcenet_datasets_workdat_data_set_citation_id_97fbad2c RENAME TO context_datasets_workdat_data_set_citation_id_97fbad2c;
ALTER INDEX sourcenet_datasets_workdat_data_set_citation_data_id_51554c0a RENAME TO context_datasets_workdat_data_set_citation_data_id_51554c0a;
ALTER INDEX sourcenet_datasets_workdatasetcitationmention_pkey RENAME TO context_datasets_workdatasetcitationmention_pkey;
ALTER INDEX sourcenet_datasets_workdat_article_id_3f2d4f2e RENAME TO context_datasets_workdat_article_id_3f2d4f2e;
ALTER INDEX sourcenet_datasets_workdat_article_data_id_1cbfbe0b RENAME TO context_datasets_workdat_article_data_id_1cbfbe0b;
ALTER INDEX sourcenet_datasets_workdat_data_set_citation_id_77554685 RENAME TO context_datasets_workdat_data_set_citation_id_77554685;
ALTER INDEX sourcenet_datasets_workdat_data_set_citation_data_id_71dd58a0 RENAME TO context_datasets_workdat_data_set_citation_data_id_71dd58a0;
ALTER INDEX sourcenet_datasets_workdat_work_data_set_citation_id_7a2fb66f RENAME TO context_datasets_workdat_work_data_set_citation_id_7a2fb66f;
ALTER INDEX sourcenet_datasets_workdat_work_log_id_b57c6c6f RENAME TO context_datasets_workdat_work_log_id_b57c6c6f;
ALTER INDEX sourcenet_datasets_datamention_pkey RENAME TO context_datasets_datamention_pkey;
ALTER INDEX sourcenet_datasets_datareference_pkey RENAME TO context_datasets_datareference_pkey;
ALTER INDEX sourcenet_datasets_datamention_article_id_48b64b25 RENAME TO context_datasets_datamention_article_id_48b64b25;
ALTER INDEX sourcenet_datasets_datamention_article_data_id_0c3a7854 RENAME TO context_datasets_datamention_article_data_id_0c3a7854;
ALTER INDEX sourcenet_datasets_datareference_article_id_45901dcc RENAME TO context_datasets_datareference_article_id_45901dcc;
ALTER INDEX sourcenet_datasets_datareference_article_data_id_0bc42052 RENAME TO context_datasets_datareference_article_data_id_0bc42052;
ALTER INDEX sourcenet_datasets_datareference_coder_id_2b1d8e57 RENAME TO context_datasets_datareference_coder_id_2b1d8e57;
ALTER INDEX sourcenet_datasets_datareference_data_set_id_13771c10 RENAME TO context_datasets_datareference_data_set_id_13771c10;
ALTER INDEX sourcenet_datasets_datareference_work_log_id_9132b352 RENAME TO context_datasets_datareference_work_log_id_9132b352;
ALTER INDEX sourcenet_datasets_datamention_data_reference_id_24fb58a7 RENAME TO context_datasets_datamention_data_reference_id_24fb58a7;
ALTER INDEX sourcenet_datasets_datamention_data_set_citation_id_e044144c RENAME TO context_datasets_datamention_data_set_citation_id_e044144c;
ALTER INDEX sourcenet_datasets_datamen_data_set_citation_data_id_efdb0c00 RENAME TO context_datasets_datamen_data_set_citation_data_id_efdb0c00;
ALTER INDEX sourcenet_datasets_datamention_work_log_id_f415f48e RENAME TO context_datasets_datamention_work_log_id_f415f48e;
ALTER INDEX sourcenet_datasets_datacontext_pkey RENAME TO context_datasets_datacontext_pkey;
ALTER INDEX sourcenet_datasets_datacontext_article_id_5897fc6f RENAME TO context_datasets_datacontext_article_id_5897fc6f;
ALTER INDEX sourcenet_datasets_datacontext_article_data_id_3803d58d RENAME TO context_datasets_datacontext_article_data_id_3803d58d;
ALTER INDEX sourcenet_datasets_datacontext_data_reference_id_935b788e RENAME TO context_datasets_datacontext_data_reference_id_935b788e;
ALTER INDEX sourcenet_datasets_datacontext_data_set_citation_id_08a23333 RENAME TO context_datasets_datacontext_data_set_citation_id_08a23333;
ALTER INDEX sourcenet_datasets_datacon_data_set_citation_data_id_eda9aec3 RENAME TO context_datasets_datacon_data_set_citation_data_id_eda9aec3;
ALTER INDEX sourcenet_datasets_datacontext_work_log_id_dbeb63d7 RENAME TO context_datasets_datacontext_work_log_id_dbeb63d7;
ALTER INDEX sourcenet_datasets_datareference_related_data_sets_pkey RENAME TO context_datasets_datareference_related_data_sets_pkey;
ALTER INDEX sourcenet_datasets_datar_datareference_id_dataset_61ffd5c8_uniq RENAME TO context_datasets_datar_datareference_id_dataset_61ffd5c8_uniq;
ALTER INDEX sourcenet_datasets_dataref_datareference_id_4a906e75 RENAME TO context_datasets_dataref_datareference_id_4a906e75;
ALTER INDEX sourcenet_datasets_dataref_dataset_id_28e8f8ae RENAME TO context_datasets_dataref_dataset_id_28e8f8ae;

/*
-- Get the table names of all the tables for this application.
--     (and get each twice for ease of making ALTER TABLE statements)
SELECT table_name, table_name
FROM information_schema.tables
WHERE table_name LIKE 'sourcenet_datasets_%'
    AND table_type='BASE TABLE';
*/

ALTER TABLE sourcenet_datasets_datareference RENAME TO context_datasets_datareference;
ALTER TABLE sourcenet_datasets_datareference_related_data_sets RENAME TO context_datasets_datareference_related_data_sets;
ALTER TABLE sourcenet_datasets_datareferencecontext RENAME TO context_datasets_datareferencecontext;
ALTER TABLE sourcenet_datasets_datareferencemention RENAME TO context_datasets_datareferencemention;
ALTER TABLE sourcenet_datasets_dataset RENAME TO context_datasets_dataset;
ALTER TABLE sourcenet_datasets_datasetcitation RENAME TO context_datasets_datasetcitation;
ALTER TABLE sourcenet_datasets_datasetcitationdata RENAME TO context_datasets_datasetcitationdata;
ALTER TABLE sourcenet_datasets_datasetidentifier RENAME TO context_datasets_datasetidentifier;
ALTER TABLE sourcenet_datasets_datasetmention RENAME TO context_datasets_datasetmention;
ALTER TABLE sourcenet_datasets_workdatasetcitation RENAME TO context_datasets_workdatasetcitation;
ALTER TABLE sourcenet_datasets_workdatasetcitationmention RENAME TO context_datasets_workdatasetcitationmention;
ALTER TABLE sourcenet_datasets_workdatasetmention RENAME TO context_datasets_workdatasetmention;
ALTER TABLE sourcenet_datasets_workresearchfield RENAME TO context_datasets_workresearchfield;
ALTER TABLE sourcenet_datasets_workresearchmethod RENAME TO context_datasets_workresearchmethod;

/*
-- Get the sequence names of all the sequences for this application.
--     (and get each twice for ease of making ALTER SEQUENCE statements)
select sequence_name, sequence_name
from information_schema.sequences
WHERE sequence_name LIKE 'sourcenet_datasets_%';
*/

ALTER SEQUENCE sourcenet_datasets_datasetcitationdata_id_seq RENAME TO context_datasets_datasetcitationdata_id_seq;
ALTER SEQUENCE sourcenet_datasets_workdatasetcitation_id_seq RENAME TO context_datasets_workdatasetcitation_id_seq;
ALTER SEQUENCE sourcenet_datasets_workdatasetmention_id_seq RENAME TO context_datasets_workdatasetmention_id_seq;
ALTER SEQUENCE sourcenet_datasets_workresearchfield_id_seq RENAME TO context_datasets_workresearchfield_id_seq;
ALTER SEQUENCE sourcenet_datasets_workresearchmethod_id_seq RENAME TO context_datasets_workresearchmethod_id_seq;
ALTER SEQUENCE sourcenet_datasets_workdatasetcitationmention_id_seq RENAME TO context_datasets_workdatasetcitationmention_id_seq;
ALTER SEQUENCE sourcenet_datasets_datareference_id_seq RENAME TO context_datasets_datareference_id_seq;
ALTER SEQUENCE sourcenet_datasets_datamention_id_seq RENAME TO context_datasets_datamention_id_seq;
ALTER SEQUENCE sourcenet_datasets_datasetidentifier_id_seq RENAME TO context_datasets_datasetidentifier_id_seq;
ALTER SEQUENCE sourcenet_datasets_dataset_id_seq RENAME TO context_datasets_dataset_id_seq;
ALTER SEQUENCE sourcenet_datasets_datasetcitation_id_seq RENAME TO context_datasets_datasetcitation_id_seq;
ALTER SEQUENCE sourcenet_datasets_datasetmention_id_seq RENAME TO context_datasets_datasetmention_id_seq;
ALTER SEQUENCE sourcenet_datasets_datacontext_id_seq RENAME TO context_datasets_datacontext_id_seq;
ALTER SEQUENCE sourcenet_datasets_datareference_related_data_sets_id_seq RENAME TO context_datasets_datareference_related_data_sets_id_seq;

